### ISSUE TITLE
Did you really make this repo to add it to your readme

### ISSUE THREAD

**Issue by greatnesshere** [renaissancedog/myprojects#2]
Did you?

**Comment by renaissancedog** [comment]
Of course not
@greatnesshere is simply throwing ridiculous accusations at me because of my superior Vim skills

**Comment by greatnesshere** [comment]
Are you sure you've even exited Vim yet?

**Comment by renaissancedog** [comment]
:wq

**Comment by greatnesshere** [comment]
@renaissancedog uses Java. Therefore, his opinions are invalid.
